# CS Club Hackathon Platform - Grafana Datasources
# Phase 6.2: Monitoring datasource configuration

apiVersion: 1

datasources:
  # Prometheus for metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      tlsSkipVerify: true
      httpMethod: POST
      queryTimeout: 300s
    version: 1

  # Loki for logs
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      tlsSkipVerify: true
      maxLines: 1000
      timeout: 60s
    version: 1

  # PostgreSQL for direct database queries
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: hackathon_db
    user: hackathon_user
    editable: true
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
    version: 1

  # Redis for cache metrics
  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis:6379
    editable: true
    jsonData:
      client: standalone
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    version: 1